### ISSUE TITLE
Add module-info

### ISSUE THREAD

**Issue by satsen** [iamgio/animated#2]
It is quite standard for JavaFX libraries and projects to be modular, can you please add a proper module-info with an appropriate name.

**Comment by satsen** [comment]
@iamgio Any reason for not doing this? Or do you just not have time right now

**Comment by iamgio** [comment]
Hi @satsen, which advantages would this bring? I don't have experience about it, plus _animated_ is written in Java 8.

**Comment by satsen** [comment]
@iamgio It would bring the advantage of not having to use the generic auto-generated (from JAR) module name and better fit in modular configurations.

You can do a multi-release JAR with module-info only for Java past 8, though I don't know why you are supporting Java 8, most JavaFX libraries have left that far behind by now.

The least you can do is to add an Automatic-Module-Name to the manifest which is better than nothing and would also be appreciated.

**Comment by iamgio** [comment]
@satsen alright, I'm going to add this and I'll probably start supporting Java 11+ only. Do you have any good reference about the module-info?

**Comment by satsen** [comment]
There are many examples :)
- ControlsFX https://github.com/controlsfx/controlsfx/blob/master/controlsfx/src/main/java/module-info.java
- FormsFX https://github.com/dlsc-software-consulting-gmbh/FormsFX/blob/master-11/formsfx-core/src/main/java/module-info.java
- Scenic View https://github.com/JonathanGiles/scenic-view/blob/master/src/main/java/module-info.java
I can make a pull request but you need to decide the module name. You can take ideas from these projects that I sent, most modular Java projects seem to use the main package name or some variant of it.

**Comment by iamgio** [comment]
@satsen while trying to deploy a snapshot containing the new module-info, I ran across this Maven error:
```
Required filename-based automodules detected: [AnimateFX-1.2.3.jar]. Please don't publish this project to a public artifact repository! *
```

After some research, I found [this](https://github.com/conveyal/kryo-tools/issues/3#issuecomment-531640162).  
I guess I have to stick to `Automatic-Module-Name` and drop the module-info file then, do you agree?

**Comment by satsen** [comment]
I don't know, the error looks like it is complaining about the jar itself? I have never published anything to maven central so I don't know. Automatic-Module-Name is good enough for now though so thanks for that
