### ISSUE TITLE
Unsearchable name

### ISSUE THREAD

**Issue by satsen** [iamgio/animated#3]
Is it possible to change the library name? `animated` is a very generic name that is hard to get search results for, even when you search for `animated javafx`.

**Comment by iamgio** [comment]
Hi, are you aware of any way of boosting a repository's chance of showing up on search engines, instead? Changing a project's name "along the way" is never convenient and I'd like to avoid that.

**Comment by satsen** [comment]
@iamgio All I can think of is having a website but that's overkill. I'm not sure if as time passes it will get higher up but I still do believe that the name is too generic.

**Comment by iamgio** [comment]
@satsen it looks like searching for _javafx implicit animations_ makes the repo appear on top (Google - I haven't verified that with other search engines).

**Comment by iamgio** [comment]
This repository now shows up in the first page when searching _animated javafx_ on Google.
