### ISSUE TITLE
AnimatedThemeSwitcher change duration

### ISSUE THREAD

**Issue by Alin63992** [iamgio/animated#4]
Hi! I have a JavaFX app window which contains a button that toggles the theme from light to dark, and i added AnimatedThemeSwitcher into the function bound to the said button. I was wondering if I could make it have another duration, like half a second or something? Because if i press that button twice or thrice after the initial change happens, the application freezes for a bit and then it switches the theme.

**Comment by iamgio** [comment]
Hi @Alin63992, you can wrap the desired `AnimationFX` into an `Animation` object in order to customize it.

```java
Animation animation = new Animation(new FadeOut()).setSpeed(2); // Twice as fast
AnimatedThemeSwitcher themeSwitcher = new AnimatedThemeSwitcher(scene, animation);
themeSwitcher.init();
```

You can also apply the animation later by calling `themeSwitcher.setOut(animation);`.

Don't call `setSpeed` directly on the `AnimationFX` object as it probably wouldn't work.

**Comment by Alin63992** [comment]
Thank you for that, now I have a faster animation! :D
About the freeze, i noticed that if i call pause on the theme switcher right after i set the scene's stylesheet, the app doesn't freeze anymore, and the button can be pressed as often as the user wants, if that helps.

**Comment by iamgio** [comment]
I can't reproduce the freeze you were experiencing. I have even tried to set the switch delay of the existing [AnimatedThemeTest](https://github.com/iamgio/animated/blob/05bf7dc29b375b32195be79e0c85c51eca98ab15/src/test/java/eu/iamgio/animatedtest/AnimatedThemeTest.java#L66) to a small value such as 0.2 seconds but the transition is still played flawlessly.

A minimal demo program would be much appreciated!

**Comment by Alin63992** [comment]
Hi! I'm not playing with a delay, not using one, I want the transition to play as soon as I click on the button that changes the theme (that being achieved by uncommenting the last line of the function below), and I want the transition to play at twice its usual speed.
``` java
@FXML
public void toggleDisplayMode() throws IOException {
    displayMode = displayMode.equals("Light") ? "Dark" : "Light";
    BufferedWriter buildUserSettings = new BufferedWriter(new FileWriter("src/main/resources/com/gendergapanalyser/gendergapanalyser/UserSettings.txt"));
    buildUserSettings.write("DisplayMode=" + displayMode + "\nLanguage=" + language);
    buildUserSettings.close();
    if (processData.predictionsGenerated) processData.createSalaryGraphWithPredictionsForEverybody();
    processData.createSalaryGraphForEverybody();
    AnimatedThemeSwitcher switchTheme = new AnimatedThemeSwitcher(Main.getCurrentStage().getScene(), new Animation(new FadeOut()).setSpeed(2.5));
    switchTheme.init();
    Main.getCurrentStage().getScene().getStylesheets().setAll(Objects.requireNonNull(getClass().getResource("Stylesheets/" + Main.displayMode + "Mode.css")).toExternalForm());
    //switchTheme.pause();
}
```
`displayMode` is a String which stores "Dark" or "Light" which represents the app's current theme. First, this variable is set, then a text file is written, then some pictures are generated which are used in parts of the program unrelated to the theme switching feature, and lastly, the theme switching happens.

**Comment by iamgio** [comment]
@Alin63992 the `AnimatedThemeSwitcher` initialization via the `init()` method should happen only once, preferably right after setting up your `Scene` object. From what I see from the first video you posted, every time the theme changes the delay gets higher: that probably happens because every time you call the `init()` method, a new listener on the scene's theme gets registered and conflicts with the others.  
The goal behind this library is to provide _implicit_ animations: you should set up your animation hooks once and the rest will be handled automatically as if you weren't animating anything. In the `AnimatedThemeSwitcher` case, this automatic thing happens whenever `Scene#getStylesheets` is affected by some change.

**Comment by Alin63992** [comment]
Got it, i did like you said and initiated the `AutomatedThemeSwitcher` object after setting up the scene. But can I pair an `AnimatedThemeSwitcher` with an `AnimatedSwitcher`? Since I'm setting the root pane as the child of the `AnimatedSwitcher`, then the switcher as the child of a `Scene` object, initiating the `AutomatedThemeSwitcher` object on the Scene throws an `IllegalStateException: The root node is not a Pane (or subclass).`
Code used:
``` java
private void goToGraphPage() throws IOException {
    AnimatedSwitcher as = new AnimatedSwitcher(new Animation(new SlideInRight()).setSpeed(2), new Animation(new SlideOutLeft()).setSpeed(2));
    Scene scene = new Scene(as);
    as.of(Main.getCurrentStage().getScene().getRoot());
    as.setChild(new FXMLLoader(getClass().getResource("DisplayEvolutionGraph-" + Main.language + ".fxml")).load());
    scene.getStylesheets().add(Objects.requireNonNull(getClass().getResource("Stylesheets/" + Main.displayMode + "Mode.css")).toExternalForm());
    //Changing the title of the current stage
    Main.getCurrentStage().setTitle(Main.language.equals("EN") ? "Evolution Graph" : Main.language.equals("FR") ? "Graphe d'Évolution" : "Grafic de Evoluție");
    //Displaying the graph page on the current stage
    Main.getCurrentStage().setScene(scene);
    switchTheme = new AnimatedThemeSwitcher(Main.getCurrentStage().getScene(), new Animation(new FadeOut()).setSpeed(2.5));
    switchTheme.init();
}
```
The `switchTheme` object is an `AnimatedThemeSwitcher` object declared outside of the function, but instantiated in it.

**Comment by iamgio** [comment]
@Alin63992 as the error message says, a `Pane` is required as the scene root, while `AnimatedSwitcher` is not. This is required because the theme switcher works by overlapping an image of the scene before the style is changed and animating it out, so that the transition is played. You can solve this by simply wrapping the `AnimatedSwitcher` into a `Pane` root.

**Comment by Alin63992** [comment]
@iamgio Thank you so much, now everything works how I want it to. You're awesome! Thanks for the help!
Cheers!
