### ISSUE TITLE
add a playback callback

### ISSUE THREAD

**Issue by SingleKey** [iamgio/animated#6]
I want to perform some actions at the end of the animation, such as closing the page, which is to pan the page out of the visible range, and then clear it. Now that there is no animation, you need to monitor the coordinates, which becomes very troublesome.I hope there is a function that can be called when the animation is finished playing.It is best to set callback functions for multiple animations separately.Or rather, this is a lifecycle. Thank you !.

**Comment by iamgio** [comment]
Hi @SingleKey, this shouldn't be hard to implement. I'll get to work as soon as I can.

**Comment by iamgio** [comment]
The feature was successfully implemented in the _animation-callbacks_ branch. I'm going to do some more testing before merging and releasing.

**Comment by iamgio** [comment]
1.3.0 was released, please check out the [release notes](https://github.com/iamgio/animated/releases/tag/v1.3.0) for more information.  
Thank you for your contribution!

**Comment by yyyyysssssi7606** [comment]
Thanks! @iamgio
