### ISSUE TITLE
Theme switching animation buggy when using GridPane as root

### ISSUE THREAD

**Issue by Alin63992** [iamgio/animated#7]
Hi again! I've encountered a small problem with using AnimatedThemeSwitcher to switch themes when using a GridPane as root.

So, I am loading an FXML file that has a GridPane containing a few nodes, and it seems the screenshot with the old theme applied gets set only on the first row and it doesn't span across all of the rows, so the animation plays on the top half of the app screen, while the bottom half is instantly displayed with the new theme applied.

https://github.com/iamgio/animated/assets/38192110/cbc94332-8cad-4faf-879e-5cf8c2206264

**Comment by iamgio** [comment]
Hi @Alin63992, only roots that allow overlapping content are supported, thus grids are not by definition. Please wrap your GridPane in a regular Pane and let me know if it fixes the issue!

**Comment by Alin63992** [comment]
Yep, it's all good now. Thank you! :D
